name: designly
favicon: null
layout_spectrum: 0.5398041002918035
typography_spectrum: 0.6116561170201749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17203570157289505
  lightness: 0.8256853013299406
  saturation: 0.12251930683851242
  rhythmicContrast: 0.13326597423292696
purpose: []
